# Generated by Django 4.2.16 on 2024-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
