# Generated by Django 4.2.16 on 2024-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_profile_cart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart_data',
            field=models.JSONField(default=dict),
        ),
    ]
